function paths = get_all_paths(start_point, end_point)
    % Return a list of all the paths from start to end generated by the
    % 12 functions and their variants
    run constants.m
    % Definir las funciones de path
    path_fns = {@path1, @path2, @path3, @path4, @path5, @path6, ...
                @path7, @path8, @path9, @path10, @path11, @path12};
    %path_fns = {@path5};  % Solo para un ejemplo, si quieres todas descomenta la línea anterior
    paths = {};

    % Obtener las coordenadas de 'end' en el sistema de coordenadas donde 'start' es (0,0,0)
    [x, y, theta] = change_of_basis(start_point, end_point);

    for i = 1:length(path_fns)
        get_path = path_fns{i};
        
        % Crear un contenedor para las trayectorias de este path
        %single_path = {};

        % Obtener las cuatro variantes para cada tipo de path
        %var1 = [single_path, get_path(x, y, theta)];  % Variante original
        var1 = get_path(x, y, theta);  % Variante original
        var2 = timeflip(get_path(-x, y, -theta));  % Variante con timeflip
        var3 = reflect(get_path(x, -y, -theta));  % Variante con reflect
        var4 = reflect(timeflip(get_path(-x, -y, theta)));  % Variante con timeflip y reflect

        % Añadir este conjunto de trayectorias (y sus variantes) a la lista principal
        if(not(isempty(var1))) paths{end+1} = var1; end
        if(not(isempty(var2))) paths{end+1} = var2; end
        if(not(isempty(var3))) paths{end+1} = var3; end
        if(not(isempty(var4))) paths{end+1} = var4; end
    end
end
